#!/bin/bash

PKG_NAME="alfred-workflow-vscode"

echo `npm view $PKG_NAME -g`

check_install=`npm list -g | grep $PKG_NAME`

# npm install $PKG_NAME@latest -g

# echo "$check_install"

if ! [[ $check_install =~ $PKG_NAME ]]; then
  # install
  npm install $PKG_NAME@latest -g
fi

echo `alfred-workflow-vscode`

echo `alfred-workflow-vscode $@`
